# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Refreshes the System Information so that it is up to date"


class Input:
    DEVICE_NAME = "device_name"
    

class Output:
    RESULT = "result"
    SUCCESS = "success"
    

class SystemRefreshInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "device_name": {
      "type": "string",
      "title": "Device Name",
      "description": "The System to perform the System Refresh on",
      "order": 1
    }
  },
  "required": [
    "device_name"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SystemRefreshOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "result": {
      "type": "string",
      "title": "Result",
      "description": "If the Inventory Refresh was successful or not",
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Boolean indicating whether the business object was successfully created",
      "order": 1
    }
  },
  "required": [
    "result",
    "success"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
