# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    ORGANIZATION = "organization"
    SSL_VERIFY = "ssl_verify"
    URL = "url"
    USERNAME_AND_PASSWORD = "username_and_password"
    

class ConnectionSchema(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "organization": {
      "type": "string",
      "title": "Organization",
      "description": "KACE organization environment",
      "default": "Default",
      "order": 2
    },
    "ssl_verify": {
      "type": "boolean",
      "title": "SSL Verify",
      "description": "Whether to access the server over HTTPS",
      "default": true,
      "order": 4
    },
    "url": {
      "type": "string",
      "title": "URL",
      "description": "Hostname of the KACE Appliance",
      "default": "vulcan.hillwood.com",
      "order": 1
    },
    "username_and_password": {
      "$ref": "#/definitions/credential_username_password",
      "title": "Username and Password",
      "description": "KACE username and password",
      "order": 3
    }
  },
  "required": [
    "organization",
    "ssl_verify",
    "url",
    "username_and_password"
  ],
  "definitions": {
    "credential_username_password": {
      "id": "credential_username_password",
      "type": "object",
      "title": "Credential: Username and Password",
      "description": "A username and password combination",
      "properties": {
        "password": {
          "type": "string",
          "title": "Password",
          "displayType": "password",
          "description": "The password",
          "format": "password"
        },
        "username": {
          "type": "string",
          "title": "Username",
          "description": "The username to log in with"
        }
      },
      "required": [
        "username",
        "password"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
